fail_fast: false
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: check-added-large-files
      args: ["--maxkb=900"]
    - id: check-merge-conflict
- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
    - id: isort
      args: [--profile=black]
- repo: https://github.com/psf/black
  rev: 25.1.0
  hooks:
    - id: black
-   repo: https://github.com/sphinx-contrib/sphinx-lint
    rev: v0.6.1
    hooks:
    - id: sphinx-lint
- repo: https://github.com/pycqa/flake8
  rev: 7.1.1
  hooks:
    - id: flake8
      args: ["--config=setup.cfg"]